version: "3.9"

services:
  postgres:
    image: postgres:14
    ports:
      - 5400:5432
    volumes:
      - ~/home/zayn/Documents/vloume:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=zayn
      - POSTGRES_USER=postgres
      - POSTGRES_DB=expense_tracker
